### ISSUE TITLE
Is there any way to adjust the small led bar on the button by MQTT?

### ISSUE THREAD

**Issue by t0ny-peng** [digiblur/TuyaDimmer-Tasmota#1]
First to say, great job. I haven't read your code yet but in the demo video it seems like the 7 small leds on the button are not adjusted to the right height when you controlled the dimmer in HA. Do you have any idea about that? Thanks.

**Comment by digiblur** [comment]
The 7 leds do move when adjusted.  The scale of the LEDs and the brightness of the bulb load itself is all handled by the secondary MCU.  The ESP8266 on board is simply a WiFi interface for the dimmer, without it, the dimmer would still function using the faceplate itself and all the actions would work from on/off and dim to bright along with the LEDs changing their scale.

**Comment by t0ny-peng** [comment]
Sorry. I came to the conclusion to early.

Best,

--------
Hao Peng
Email: hao@pengs.us
