### ISSUE TITLE
Edit Settings

### ISSUE THREAD

**Issue by chris8837** [digiblur/TuyaDimmer-Tasmota#2]
How would I go about building my own firmware with my own lat-long and time zone settings. 

Right now I use ATOM and PlatformIO to build a custom firmware. 

Is there another way with this version?  I don’t see the platformIO directory 

Thanks. New to this and I ordered one, but use tasmota for a few time settings.

**Comment by digiblur** [comment]
Actually if you want to grab the latest development branch of Tasmota firmware my pull request was merged a week or two ago.  I was waiting for the production release to be sent out first before I updated this page.

**Comment by chris8837** [comment]
Cool!!  So I would just grab it, edit it like normal, then build?

Is yours listed as a different name or is it still Tuya?

**Comment by digiblur** [comment]
See here:  https://github.com/arendst/Sonoff-Tasmota/pull/4075

**Comment by digiblur** [comment]
Yes, you can pull/clone the development build and they have on their Wiki how to build in PlatformIO and/or Arduino IDE.  

The Tuya Dimmer will be in the drop down as the device type in the Tasmota GUI once you flash.

**Comment by digiblur** [comment]
@chris8837 Also if you don't want to build you can pull the latest nightly builds from here that will have the Tuya Dimmer support in it already.  You should be able to modify the time zone stuff via the Tasmota commands via the console in the GUI.

http://thehackbox.org/tasmota/
