### ISSUE TITLE
Moes DS01C

### ISSUE THREAD

**Issue by jasonyork** [digiblur/TuyaDimmer-Tasmota#3]
Sorry, this isn't an issue, but wasn't sure of the best way to contact you.  I've seen a lot of your work on the Tuya dimmers and I've been trying to get one working I recently purchased with Tasmota.  It's a Moes DS01C, which might be a bit different than the ones you worked on. 

I did get it flashed.  Using the device template 54, it has no toggle button, and dimming somewhat works, but only all the way low or high.

Below is a picture of it.  Any info or tips you could give me on getting this to work would be appreciated.  Thanks!

![image](https://user-images.githubusercontent.com/1487146/61594946-a27cdb80-abb6-11e9-945b-e69cf995dfb0.png)

**Comment by digiblur** [comment]
I know there was some issue with 6.6.0 and the Tuya dimmers showing too many toggles. I would try the latest dev version.  http://thehackbox.org/tasmota/020300/sonoff.bin

**Comment by digiblur** [comment]
Hit me up on Discord as it would be easier to discuss this.  https://discord.gg/cPAxGqm

**Comment by pauldogg** [comment]
How did you flash yours?
I have V G Tx Rx and GPIO0 all soldered and connected (GPIO0 to G at boot) and i am unable to flash. any ideas?
Thanks

**Comment by digiblur** [comment]
You could use Tuya Convert on them if you can't get the hardware to work.

**Comment by brad55590** [comment]
Did you manage to get this dimmer working correctly?

I just bought one too, but cannot get the dimmer to work correctly.

**Comment by jasonyork** [comment]
@brad55590 - I did end up getting it working by using the latest (master) branch version of Tasmota.  However when I hooked it up to my light fixture, it generated a loud humming noise, so I took it out and haven't looked at it since :(

**Comment by brad55590** [comment]
Ahh. Ive got the latest firmware. I can get it to turn on and off. But the dimming does not work.

Also have the ds01c and i can only find ds01_1 templates and configs.

**Comment by digiblur** [comment]
Did you get it flashed?

If you get a humming then your light doesn't support dimming.

**Comment by brad55590** [comment]
Yup i got it flashed. Globes support dimming as i replaced a dumb dimmer with this dimmer. No humming. And before i flashed it, i tested using the default firmware and all worked fine. I can turn lights on and off and dim with the switch. I can turn on and off using tasmota. But dimming using tasmota doesnt work.

**Comment by digiblur** [comment]
You set the dimmer range and picked the Tuya MCU GPIO pins? https://youtu.be/_3WW4NVYHrU

**Comment by brad55590** [comment]
@digiblur  Thank you, all sorted. dimming works 100%.

My Issue was the dpid and dimmer range was not set correctly.

**Comment by digiblur** [comment]
Nice!  Woot!
